### ISSUE TITLE
SBT 0.12.4 Supported?

### ISSUE THREAD

**Issue by gagnechris** [sbt/jacoco4sbt#10]
I'm still using SBT 0.12.4 and curious to know if it is still supported?  Here is I see after adding addSbtPlugin("de.johoop" % "jacoco4sbt" % "2.1.4")

[info] Resolving de.johoop#jacoco4sbt;2.1.4 ...
[warn]  module not found: de.johoop#jacoco4sbt;2.1.4
[warn] ==== typesafe-ivy-releases: tried
[warn]   http://repo.typesafe.com/typesafe/ivy-releases/de.johoop/jacoco4sbt/scala_2.9.2/sbt_0.12/2.1.4/ivys/ivy.xml
[warn] ==== sbt-plugin-releases: tried
[warn]   http://scalasbt.artifactoryonline.com/scalasbt/sbt-plugin-releases/de.johoop/jacoco4sbt/scala_2.9.2/sbt_0.12/2.1.4/ivys/ivy.xml
[warn] ==== local: tried
[warn]   /Volumes/MacintoshHD/Users/gagnechris/.ivy2/local/de.johoop/jacoco4sbt/scala_2.9.2/sbt_0.12/2.1.4/ivys/ivy.xml
[warn] ==== getty-releases: tried
[warn]   http://sea-ops-artifacts-01.amer.gettywan.com:8081/nexus/content/repositories/releases/de/johoop/jacoco4sbt_2.9.2_0.12/2.1.4/jacoco4sbt-2.1.4.pom
[warn] ==== public: tried
[warn]   http://repo1.maven.org/maven2/de/johoop/jacoco4sbt_2.9.2_0.12/2.1.4/jacoco4sbt-2.1.4.pom
[info] Resolving com.escalatesoft.subcut#subcut_2.9.2;2.0 ...
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: de.johoop#jacoco4sbt;2.1.4: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn]  Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn]      de.johoop:jacoco4sbt:2.1.4 (sbtVersion=0.12, scalaVersion=2.9.2)
[warn]
sbt.ResolveException: unresolved dependency: de.johoop#jacoco4sbt;2.1.4: not found

**Comment by benmccann** [comment]
We aren't likely to support SBT 0.12
