### ISSUE TITLE
jacoco4sbt unable to perform code coverage with play 2.3.1

### ISSUE THREAD

**Issue by rokumar7** [sbt/jacoco4sbt#35]
Hi,

I am using jacoco4sbt to perform code coverage for an application deployed in play 2.3.1 (activator based). 

When I run 'activator jacoco:cover' command, it gives me the following output.

[info] Lines: 0% (>= required 0.0%) covered, 1148 of 1148 missed, OK
[info] Instructions: 0% (>= required 0.0%) covered, 6535 of 6535 missed, OK
[info] Branches: 0% (>= required 0.0%) covered, 478 of 478 missed, OK
[info] Methods: 0% (>= required 0.0%) covered, 264 of 264 missed, OK
[info] Complexity: 0% (>= required 0.0%) covered, 503 of 503 missed, OK
[info] Class: 0% (>= required 0.0%) covered, 81 of 81 missed, OK
[info] Check /home/gdev/fase/v2.0/fase/platform/service-components/Job/eqx-fase-product-dist-job/target/scala-2.11/jacoco for detail report

Why is it failing to do code coverage ?

Thanks,
Rohit

**Comment by benmccann** [comment]
I believe this works with newer version of both plugins
