### ISSUE TITLE
Upgrade jacoco library to 0.7.8

### ISSUE THREAD

**Issue by margussipria** [sbt/jacoco4sbt#47]
Just so sbt-update would not show that new version is available :smile:

**Comment by tonicebrian** [comment]
We need that to show reports in Jenkins since it seems that 0.7.5 doesn't play with Jenkins Jacoco plugin. See https://issues.jenkins-ci.org/browse/JENKINS-28652

**Comment by linjer** [comment]
I've taken a step towards addressing this in PR #67 . After this refactoring, it appears that we should be able to simply bump the version to 7.9 and cut a release.

**Comment by benmccann** [comment]
@linjer it's not as simple as just bumping the version number unfortunately. Bumping to `0.7.7` or beyond causes the tests to fail

**Comment by linjer** [comment]
@benmccann You're right. I made a mistake in my previous tests by not updating the version tested against. They were previously passing against plugin version 2.2.0, which was using jacoco 0.7.5. I'll look into upgrading soon.

**Comment by linjer** [comment]
I believe this should now be addressed by PR #72 .

**Comment by benmccann** [comment]
Fixed now. Thanks @linjer !
