### ISSUE TITLE
java.io.IOException: Error while instrumenting class Global$1.class with Java 8

### ISSUE THREAD

**Issue by woezelmann** [sbt/jacoco4sbt#52]
After updating a play project to JAVA 8 instrumentation ("jacoco:cover") breaks with following error: `java.io.IOException: Error while instrumenting class Global$1.class`

Is this a know issue?

**Comment by emlagowski** [comment]
I have the same problem. Have you solved it?

**Comment by woezelmann** [comment]
No. Just removed code coverage.

**Comment by rozuur** [comment]
I faced this issue with 2.1.4, and after updating to latest version this got resolved

**Comment by benmccann** [comment]
This should be fixed by newer versions
