### ISSUE TITLE
jacoco:check it-jacoco:cover + threshold values

### ISSUE THREAD

**Issue by jarlah** [sbt/jacoco4sbt#53]
I am not able to set threshold values that kick in for it-jacoco:cover. I can set thresholds for jacoco:cover, and i have tried the snapshot 2.1.7 and using aggregateThreshold on both jacoco and it-jacoco to no avail. 

Any help on this?

**Comment by cowboygneox** [comment]
@jarlah How did you set thresholds at all? I don't see that in the documentation anywhere...

**Comment by jarlah** [comment]
@cowboygneox Simple. Searched on google and found Treshold example configuration in the source of this project. 
https://github.com/sbt/jacoco4sbt/blob/master/src/main/scala/de/johoop/jacoco4sbt/Keys.scala#L44

Since IntegrationTest extend from Keys its a wild assumption that it should also work for integration tests.

**Comment by cowboygneox** [comment]
@jarlah That's awesome. Thanks!

**Comment by jarlah** [comment]
@cowboygneox No problems. If you for some reason find out how we can make this work for integration test coverage please let me know. I am hacking the sbt Test config atm listening to a system property and then including unmanagedsourcedirectory for integration tests into test config to get coverage on all tests both junit and integration

**Comment by jarlah** [comment]
God this is so embarrassing... 

```
itJacoco.thresholds in itJacoco.Config := Thresholds(instruction = 35, method = 40, branch = 30, complexity = 35, line = 38, clazz = 40)
``` 

I had tried:

```
itJacoco.thresholds in jacoco.Config := Thresholds(instruction = 35, method = 40, branch = 30, complexity = 35, line = 38, clazz = 40)
```

but oviously the convention that you need to repeat itJacoco in two places made me use up to three days on this shit. Should really not have to think so much about this. Ideally I would like something more concise, like this code:

```
thresholds in itJacoco.Config := Thresholds(instruction = 35, method = 40, branch = 30, complexity = 35, line = 38, clazz = 40)
```

**Comment by jarlah** [comment]
Issue can be closed. But documentation NEEDS to be updated with configuration for both junit tests and integration tests, so we (developers) can use less time spent on searching google and browsing the code for clues and getting our work done...

**Comment by tkidman** [comment]
Thanks for this - I had no idea how to configure these params.  Examples on the net are sparse ...
