### ISSUE TITLE
Please deploy 2.1.7

### ISSUE THREAD

**Issue by cowboygneox** [sbt/jacoco4sbt#55]
I see there is support for aggregated builds, which I could really use right now. Can we make a deploy sometime soon?

**Comment by ronlawrence3** [comment]
I have been waiting for this also. I'm currently using a really awful hack to merge my jacoco.exec files, and would really like to use this!

**Comment by cowboygneox** [comment]
@ronlawrence3 I successfully built this plugin locally, installed it as a project/lib, and we are using it in our process right now. It was a little difficult to figure it out without docs, but I did get it working to aggregate coverage.

**Comment by stuartgmilton** [comment]
Please please please deploy 2.1.7

**Comment by stuartgmilton** [comment]
@cowboygneox Any chance you could outline you steps?

**Comment by cowboygneox** [comment]
@stuartgmilton I believe all I did was checkout the repo and do `sbt publishLocal`, and then I took the jar that was put into my local ivy cache into my project's `project/lib` folder. Try that.

**Comment by analytically** [comment]
+1

**Comment by margussipria** [comment]
Isn't 2.2.0 available now? this could be closed?
